version: '{build}'
os: 'Windows Server 2012'
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.6.0\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-Xmx1g
  - cmd: SET JAVA_OPTS=-Xmx1g
build_script:
  - ./mvnw.cmd package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
test_script:
  - ./mvnw.cmd verify --fail-at-end -U -V
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
branches:
  only:
   - master
   - develop

